### ISSUE TITLE
Request: go client

### ISSUE THREAD

**Issue by i** [button/divvy#21]
Hi Button, it would be great to have an open source go client.

Anything I can do to help with that? 😁

**Comment by mikeybtn** [comment]
Hey @i ! Sorry we missed this... Exciting to be visited by a GitHub celebrity! :-)

We do have a go client, I'd be happy to share it. Let me look into getting it broken out of our private repo.

**Comment by mikeybtn** [comment]
https://github.com/button/divvy-client-go

![](https://media.giphy.com/media/8hZpPt93ycykaRPsSp/giphy.gif)
